### ISSUE TITLE
按照教程配置，仍然不行

### ISSUE THREAD

**Issue by stupidoge** [eliaszon/Programmers-Overseas-Job-Interview-Handbook#6]
我用的是clashX，把direct改成proxy还是会出现问题；全局模式倒没什么问题。
后来看到大佬的帖子，下载了一个clash for windows(在macos上，结果还是不行，哪怕加了parser。
求大佬解决

**Comment by eliaszon** [comment]
具体的原因可能比较复杂，比如我帮一个朋友远程修理这个问题，最后发现是因为他装了某个第三方中文版Clash for Windows 。你也可以检查一下。
https://t.me/eliaseliaszeng
这是我的tg，可以私聊我一下，可以截图把你的配置和Clash的各个界面截图给我看一看，不过最近白天在上班不一定能看到消息。
