### ISSUE TITLE
behavioral questions的两个notion链接失效了,求更新

### ISSUE THREAD

**Issue by Jansson8964** [eliaszon/Programmers-Overseas-Job-Interview-Handbook#7]

**Comment by eliaszon** [comment]
https://twitter.com/iTeaTime_/status/1542389148538920960

参考这张图即可。应该是作者的分享出了问题。

其实 behavior questions 网上很多的，上 Youtube 随手一搜就一大堆。

**Comment by eliaszon** [comment]
本handbook已更新。
